services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./data/documents:/app/data/documents
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    environment:
      API_URL: http://api:8000
    volumes:
      - ./data/documents:/app/data/documents
      - ./chroma_db:/app/chroma_db
    ports:
      - "8501:8501"
    depends_on:
      - api
